#!/bin/bash

#/ NAME
#/     poop -- chef-like bash configuration management
#/
#/ SYNOPSIS
#/     poop

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"
require 'poop'

# entry point
function main {
  directory "meh"
    mode 0750
  end

  directory "meh/mon"
    mode 0700
  end
}

# parse the command-line
parse_command_line "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# pass arguments to entry point
main "$@"
