#!/bin/bash

#/ NAME
#/     poop -- chef-like bash configuration management
#/
#/ SYNOPSIS
#/     poop

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line

# entry point
function main {
  require 'poop'

  local nm_recipe
  for nm_recipe in "$@"; do
    recipe "$nm_recipe"
  done
}

require 'sub' "$BASH_SOURCE" "$@"
